### PR TITLE
fixes non-empty bash history

### PR DESCRIPTION
**Pull request by pachadotdev**

### CODE REVIEW

**Comment by psolymos** [comment]
@pachamaltese thanks for the PR. The lines from `setup.sh` does not show up in `/root/.bash_history` on the droplet because it is not interactive shell. Can you explain why removing `/root/.bash_history` in this case is beneficial?

**Comment by psolymos** [comment]
Just to clarify: the `setup.sh` is used to update the droplet and shinyproxy configs *after* the new droplet is created (from an image). The bash history cleanup needs to happen before the image creation for the marketplace app, and I used `history -c` for that which left only `shutdown -h now` in the history (I could see that when testing). Thanks for the hint though!

**Comment by pachadotdev** [comment]
Got it! Where is the script that creates the image?

**Comment by psolymos** [comment]
It is not yet a script (although I am thinking about using the recommended python based approach next time). It is just a set of instructions in `setup.md` I am following manually.

**Comment by pachadotdev** [comment]
Check my rstudio droplet on github.com/pachamaltese

**Pull request closed without merging**
